name: Angular CI

on:
  push:
    branches: [ "master" ]   # CD only after merge
  pull_request:
    branches: [ "master" ]   # CI only

permissions:
  contents: write   # required for gh-pages push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run unit tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular app (Production)
        run: npm run build -- --configuration production --base-href /ci-cd-ga/

      # ðŸš€ CD â€” ONLY after merge to master
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          npx angular-cli-ghpages \
          --dir=dist/ci-cd-ga/browser \
          --no-silent
